import type { Metadata } from "next";
import { Share_Tech_Mono, Anton, Rajdhani } from "next/font/google";
import "./globals.css";

const shareTech = Share_Tech_Mono({
  weight: "400",
  variable: "--font-sharetech",
  subsets: ["latin"],
});

const anton = Anton({
  weight: "400",
  variable: "--font-anton",
  subsets: ["latin"],
});

const rajdhani = Rajdhani({
  weight: ["600", "700"],
  variable: "--font-rajdhani",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${shareTech.variable} ${anton.variable} ${rajdhani.variable} min-h-full flex flex-col antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
